### ISSUE TITLE
Webclient asking for password

### ISSUE THREAD

**Issue by markrutten** [Kabe0/deluge-windscribe#1]
When trying to open de webclient on port 8112 its asking for a password but this password is nowhere mentioned in the installation description.

**Comment by Kabe0** [comment]
Under the Authorization section there needs to be configured a /config/auth.conf configured for the container to automatically connect to the container. 

Depending where you decide to mount the /config folder volume, there needs to be a file labeled auth.conf configured with the following details

`<username>
<password>
<location|best>`

**Comment by guice** [comment]
The issue is the default password of the web UI. It's `deluge` and should be commented within the README.

**Comment by Kabe0** [comment]
@guice  Did not notice the webclient message in the original question. My bad, Will add that note in.
