### ISSUE TITLE
Windscribe will not connect - container ignores auth.conf

### ISSUE THREAD

**Issue by OC-Rookier** [Kabe0/deluge-windscribe#11]
I'll preface this by saying that I am not the most experienced with Docker and GitHub, but I am willing to give more information if needed.

I used this image for the past six months or so without any issues via the `docker run` command, and it was a whole lot simpler than trying to install windscribe through a qbittorrent container. A few days ago, however, I decided to ditch `docker run` commands, and try out `docker-compose`. Deploying my other containers worked fine, but for whatever reason, this container kept failing to connect to windscribe, despite having an auth.conf file bound to it. I tried using the `docker run` command again, but it kept spitting out the same result over and over again. My host is a Raspberry Pi 4 with Raspbian (lastest version based off Debian 10). Attached is a portion of my `docker-compose.yml` file.

The only things that the log says is this:

Initializing Container,
Using config file /config/auth.conf.,
/usr/bin/init.py:15: DeprecationWarning: 'U' mode is deprecated,
  with open(vpnAuth, 'rU') as f:,
Starting windscribe ... OK,
Traceback (most recent call last):,
  File "/usr/bin/init.py", line 45, in <module>,
    raise Exception(f"Unable to properly connect to Windscribe. Make sure username/password is correct in the {vpnAuth} file."),
Exception: Unable to properly connect to Windscribe. Make sure username/password is correct in the /config/auth.conf file.

Then the container restarts right after because I my compose file is set to automatically restart containers unless they are stopped.

[docker-compose.txt](https://github.com/Kabe0/deluge-windscribe/files/5851280/docker-compose.txt)

EDIT: log pasted backwards for some reason, and added docker-compose.yml file.

**Comment by Kabe0** [comment]
Maybe check one of these issues

1. Docker network is having issues and the OS just needs a full restart
2. If the auth.conf file was created in windows, it can create bad characters
3. auth.conf does not have the right read/right permissions
4. The network adapter for the Pi is not behaving nicely. Try setting the network_mode to "host" to see if that resolves the ip issue.

Let me know if any of those work... Also the image could be out of date. You could run ```docker-compose pull``` to get the latest updates.

**Comment by OC-Rookier** [comment]
1. Restarting the host had no affect
2. auth.conf was created on the host itself via `nano`.
3. Through the host, I went as far as to give the folder and `sudo chmod -R 777` the folder containing the auth.conf file, but again, no effect.
4. Setting the network mode to host changed nothing.

I also tried pulling the latest image, but that did nothing as well.

**Comment by OC-Rookier** [comment]
Update: went back to previous versions and found that the issue came up in 1.8.8, but was not present in 1.8.3 or 1.7.2. I assume that other previous versions are fine as well.

**Comment by Kabe0** [comment]
I upgraded Ubuntu to version 20.04. So maybe that's the issue, though it could also be one other thing. If you have a chance, can you try kabe0/deluge-windscribe:beta-armv7 and let me know if the issue persists. I may have to revert to the older version of Ubuntu if you are still having issues.

**Comment by OC-Rookier** [comment]
Issue persists.

From the logs (line number in the /usr/bin/init.py script has changed?):

Initializing Container,
Using config file /config/auth.conf.,
/usr/bin/init.py:15: DeprecationWarning: 'U' mode is deprecated,
  with open(vpnAuth, 'rU') as f:,
Starting windscribe ... OK,
Settings location to best,
Traceback (most recent call last):,
  File "/usr/bin/init.py", line 47, in <module>,
    raise Exception(f"Unable to properly connect to Windscribe. Make sure username/password is correct in the {vpnAuth} file."),
Exception: Unable to properly connect to Windscribe. Make sure username/password is correct in the /config/auth.conf file.

**Comment by Kabe0** [comment]
Thanks for checking. That will help me a lot. Will patch the issue this weekend.

**Comment by OC-Rookier** [comment]
That is correct. 1.8.3 connects to Windscribe and I can add torrents without issue. Let me know if you need any more information or tests run.

**Comment by Kabe0** [comment]
This is going to take me a bit longer to fix. It's specifically an issue with Ubuntu 20.04 resolv.conf which is being managed by docker not my own container. I am going to try using a thin client like Alpine so I have better control and will see if that solves the issues.

**Comment by Hukuma1** [comment]
Just wanted to confirm same issue. Reverting back to `1.8.3` is working right now.

**Comment by Kabe0** [comment]
I have not yet had time to re-write it, but i might have to push in the older version of Ubuntu in the meantime.

**Comment by OC-Rookier** [comment]
No worries. Take your time.

**Comment by Kabe0** [comment]
Alright, I have a new build to test. I created a kill listener that terminates the entire Windscribe session. On my local that resolved the issue which had in the event that a container was stopped then started again, that it would not have the ability to resolve DNS values.

You can grab the build by setting your image to ```kabe0/deluge-windscribe:test```.

**Comment by OC-Rookier** [comment]
The new image works for me now. I can now access the WebUI and download again. I noticed this warning in the logs, but they didn't cause any issues for me.

KeyError: 'ngettext',
    builtins.__dict__['_n'] = builtins.__dict__['ngettext'],
  File "/usr/lib/python3/dist-packages/deluge/i18n/util.py", line 118, in setup_translation,
'ngettext',
Traceback (most recent call last):,
Unable to initialize gettext/locale!,

**Comment by Kabe0** [comment]
Yea I have a note for that. It's a deluge issue, not mine so it's really up to them to fix.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by OC-Rookier** [comment]
In that case, I believe this issue is closed. Thank you!
