### ISSUE TITLE
N data traffic

### ISSUE THREAD

**Issue by ronioncloud** [Kabe0/deluge-windscribe#12]
The deluge starts, however, does not generate data.
 
 
Status: Downloaded newer image for kabe0/deluge-windscribe:latest
Initializing Container
Using VPN_USERNAME and VPN_PASSWORD to login.
Starting windscribe ... OK
Settings location to best
Initializing Deluge
Configuring firewall settings
Setting UID to 1000
usermod: no changes
Setting GID to 1000
Deluged Init
Unable to initialize gettext/locale!
'ngettext'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/i18n/util.py", line 118, in setup_translation
    builtins.__dict__['_n'] = builtins.__dict__['ngettext']
KeyError: 'ngettext'

**Comment by Kabe0** [comment]
You mean you have no connection to the VPN? There are no obvious errors I see on the logs here. The localization is all about translations and does not effect the deluge app itself. 

Does your Deluge instance have an IP address listed in the bottom right corner?

**Comment by ronioncloud** [comment]
> You mean you have no connection to the VPN? There are no obvious errors I see on the logs here. The localization is all about translations and does not effect the deluge app itself.

There is no IP address listed in the bottom right corner :/ 

![ip](https://user-images.githubusercontent.com/69330915/107797683-f66f8800-6d39-11eb-8e29-6a05fce71f73.JPG)

**Comment by ronioncloud** [comment]
"sudo docker exec -it aea8157658b7 windscribe status
windscribe -- pid: 17, status: running, uptime: 1m, %cpu: 0.0, %mem: 0.2
IP: 52.15.XX.XX
DISCONNECTED
"
So, i run:
"sudo docker exec -it aea8157658b7 windscribe connect best
Connecting to US East Washington DC Precedent (UDP:443)
Firewall Enabled
/etc/resolv.conf is not a symlink, this may break DNS
Connected to US East Washington DC Precedent
Your IP changed from 52.15.XX.XX to 23.105.XX.XX"

it worked for a few seconds, and soon after it returned to my ip at windscribe status. ;/

**Comment by Kabe0** [comment]
Ok so that's a new one. What is the OS of your main computer? What did the command look like you used to execute the container?

One thing you can try is ```network_mode host```. You will need to remove the ports. This runs the container on the same level as your actual computer.

This does not look like a container issue, so it's probably something system related or a windscribe-cli issue.

**Comment by ronioncloud** [comment]
> Ok so that's a new one. What is the OS of your main computer? What did the command look like you used to execute the container?
> 
> One thing you can try is `network_mode host`. You will need to remove the ports. This runs the container on the same level as your actual computer.
> 
> This does not look like a container issue, so it's probably something system related or a windscribe-cli issue.

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

"sudo docker run \
 -v /home/myuser/config:/config \
 -v /home/myuser/downloads:/downloads \
 -p 8112:8112 \
 -p 58846:58846 \
 --dns 8.8.8.8 \
 --cap-add=NET_ADMIN \
 --device /dev/net/tun:/dev/net/tun \
 --name deluge-windscribe \
 kabe0/deluge-windscribe"

**Comment by Kabe0** [comment]
Try this out
```sudo docker run
-v /home/myuser/config:/config
-v /home/myuser/downloads:/downloads
--network host 
--dns 8.8.8.8
--cap-add=NET_ADMIN
--device /dev/net/tun:/dev/net/tun
--name deluge-windscribe
kabe0/deluge-windscribe```

**Comment by TheOriginalXman** [comment]
I am running the same OS and running into a similar problem. When I initially start the container windscribe is connected and under status shows

`root@9204ae4a2093:/# windscribe status
windscribe -- pid: 18, status: running, uptime: 3m, %cpu: 0.0, %mem: 1.6
IP: 172.241.214.243
CONNECTED -- US-W UDP (443)`

however a minute later reverts to my actual ip

`root@9204ae4a2093:/# windscribe status
windscribe -- pid: 18, status: running, uptime: 4m, %cpu: 0.0, %mem: 1.6
IP: 76.xx.xx.xx
CONNECTED -- US-W UDP (443)`

It still shows that it is connected to US-W and in deluge I see 172.241.214.243 as my external IP address.

**Comment by ronioncloud** [comment]
> Try this out
> 
> ```
> -v /home/myuser/config:/config
> -v /home/myuser/downloads:/downloads
> --network host 
> --dns 8.8.8.8
> --cap-add=NET_ADMIN
> --device /dev/net/tun:/dev/net/tun
> --name deluge-windscribe
> kabe0/deluge-windscribe
> ```
> 
> I am on the same version of Ubuntu so the OS should not in itself be an issue...
Error (i already try chmod 777 -R deluge-windscribe(path) and chmod 777 -cR path.
"Status: Downloaded newer image for kabe0/deluge-windscribe:latest
Initializing Container
Using config file /config/auth.conf.
/usr/bin/init.py:15: DeprecationWarning: 'U' mode is deprecated
  with open(vpnAuth, 'rU') as f:
Traceback (most recent call last):
  File "/usr/bin/init.py", line 15, in <module>
    with open(vpnAuth, 'rU') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/config/auth.conf'

Using flags user/password changes the IP of the machine and I lose the connection.




"

**Comment by ronioncloud** [comment]
Non-authoritative 'Host not found'  is a problem with DNS?
Error timeout /  Operation not permittied.

![Captura de Tela (49)](https://user-images.githubusercontent.com/69330915/107851769-1dd25d80-6deb-11eb-98d7-ee07d1971849.png)
![Captura de Tela (50)](https://user-images.githubusercontent.com/69330915/107851770-1f038a80-6deb-11eb-8beb-cdd23a50ffbc.png)

**Comment by Kabe0** [comment]
I have seen that happen. It's not an actual dns issue, but sometimes torrent seeds go down. By default deluge only checks the first tracker in a torrent file  which can be a problem.

Enable LtConfig and turn on "announce to all trackers" and "announce to all tiers".

Note: the deluge will still say that dns error.

#Using flags user/password changes the IP of the machine and I lose the connection

I'm not quite sure what you mean by flags changing the ip. Can you clarify further?

**Comment by ronioncloud** [comment]
Now it's working, the average speed is 400 kbps?

I would like a help to access remotely, I can access only in the VPS http://localhost:8112/

**Comment by Kabe0** [comment]
Your speeds are going to be based on a bunch of factors. Note a VPN runs about 1/3 slower than a native connection.

It should work remotely on your home network out of the gate. However if the Ubuntu system has a firewall turned on such as UFW you will need to explicitly open the ports.
