### ISSUE TITLE
Container configured with defaults doesn't start because of AttributeError on line 7

### ISSUE THREAD

**Issue by CoolSpot** [Kabe0/deluge-windscribe#16]
By default, the environment variable "LEGACY_IPTABLES" is not present.

Running container without that variable causes this error:
```
# /usr/bin/python3 /usr/bin/init.py
Initializing Container
Traceback (most recent call last):
  File "/usr/bin/init.py", line 7, in <module>
    if os.getenv('LEGACY_IPTABLES', True).lower() in ['true', '1']:
AttributeError: 'bool' object has no attribute 'lower'
```

Introduced with [this commit](https://github.com/Kabe0/deluge-windscribe/commit/71cc4c4c222555c8b534fb8fd2b9ab5acb6b1cf4#diff-3fbc5e10c7802584d58c420cbb617047ca3dd58474444f55496fe4e89ccf647b).

**Comment by Kabe0** [comment]
Good catch. Patching now with 1.9.1

**Comment by Kabe0** [comment]
I have pushed in a new image. Please let me know if the problem is now resolved for you.

**Comment by CoolSpot** [comment]
Tested, all good, thank you!
