### ISSUE TITLE
Bash 100% CPU

### ISSUE THREAD

**Issue by louis6999** [Kabe0/deluge-windscribe#18]
Hi,

does it normal that i have a bash at 100% cpu when i run my container ?

top - 17:48:30 up 5 days,  2:10,  0 users,  load average: 1.58, 1.43, 1.63
Tasks: 183 total,   2 running, 178 sleeping,   0 stopped,   3 zombie
%Cpu(s): 23.5 us,  8.8 sy,  0.0 ni, 67.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7796.1 total,    134.2 free,    956.0 used,   6705.9 buff/cache
MiB Swap:   7999.9 total,   7979.7 free,     20.2 used.   6516.5 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 **1560 root      20   0    3836   2956   2736 R 100.0   0.0 347:20.63 bash**
30903 root      20   0 1391152 228312  36980 S  13.3   2.9  50:26.06 motion
    1 root      20   0  171044  10808   7792 S   0.0   0.1   0:50.24 systemd

**Comment by Kabe0** [comment]
I have a patch coming. It's not actually running at 100%, but the bash loop to keep the dockerfile running was acting a bit too aggressive.

The purpose is to track kill signals from docker so that it properly turns off the Windscribe settings.

**Comment by Kabe0** [comment]
Ok pushing in a patch 1.9.2. You can pull either the latest branch or that specific commit and let me know if the issue is resolved at your end. Give it a few minutes though.

**Comment by louis6999** [comment]
Hi,

It's perfect. Thanks !
