### ISSUE TITLE
Cannot connect to windscribe - Timeout

### ISSUE THREAD

**Issue by L44RS** [Kabe0/deluge-windscribe#22]
Hi! Trying to run the image in docker on a WSL2 VM. Correct ports are already forwarded to the actual ethernet interface. 

When I try to run the container, the logs show that windscribe has started. Whilst setting the location however, the timeout error occurs. What am I doing wrong?

Logs:
_Initializing Container,
Using config file /config/auth.conf.,
/usr/bin/init.py:23: DeprecationWarning: 'U' mode is deprecated,
  with open(vpnAuth, 'rU') as f:,
Starting windscribe ... OK,
Settings location to Bicycle,
Traceback (most recent call last):,
  File "/usr/bin/init.py", line 52, in <module>,
    cond = child.expect(['Please login to use Windscribe', 'Service communication error', pexpect.EOF], timeout=50),
  File "/usr/local/lib/python3.9/dist-packages/pexpect/spawnbase.py", line 343, in expect,
    return self.expect_list(compiled_pattern_list,,
  File "/usr/local/lib/python3.9/dist-packages/pexpect/spawnbase.py", line 372, in expect_list,
    return exp.expect_loop(timeout),
  File "/usr/local/lib/python3.9/dist-packages/pexpect/expect.py", line 181, in expect_loop,
    return self.timeout(e),
  File "/usr/local/lib/python3.9/dist-packages/pexpect/expect.py", line 144, in timeout,
    raise exc,
pexpect.exceptions.TIMEOUT: Timeout exceeded.,
<pexpect.pty_spawn.spawn object at 0x7f03e1e06cd0>,
command: /usr/bin/windscribe,
args: ['/usr/bin/windscribe', 'connect', 'Bicycle'],
buffer (last 100 chars): b'\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-',
before (last 100 chars): b'\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-',
after: <class 'pexpect.exceptions.TIMEOUT'>,
match: None,
match_index: None,
exitstatus: None,
flag_eof: False,
pid: 145,
child_fd: 6,
closed: False,
timeout: 30,
delimiter: <class 'pexpect.exceptions.EOF'>,
logfile: None,
logfile_read: None,
logfile_send: None,
maxread: 2000,
ignorecase: False,
searchwindowsize: None,
delaybeforesend: 0.05,
delayafterclose: 0.1,
delayafterterminate: 0.1,
searcher: searcher_re:,
    0: re.compile(b'Please login to use Windscribe'),
    1: re.compile(b'Service communication error'),
    2: EOF,_

**Comment by L44RS** [comment]
Forgot to mention, when running the container without the VPN enabled I do have internet access.

**Comment by Kabe0** [comment]
Hmm it might be the config file. Does using the login variables work?

**Comment by L44RS** [comment]
Whoa, that's a quick response. Awesome! I've tried setting the env variables, and I thought it gave the same result. It seems that it is still taking the auth.conf file as a source. I've now removed that file, but now I get the error that auth.conf cannot be found..

Is there something I need to set in order for it to not use the auth.conf file?

**Comment by L44RS** [comment]
Owwww, wait. I'm setting the webproy username and password. Whoops. Let's check whether it works when I actually set the correct env variables.

**Comment by L44RS** [comment]
Issue persists unfortunately. Could it have something to do with the device not being correct for a WSL2 installation? Or would the throw other errors?

Appreciate your work!

Logs:
Initializing Container,
Using VPN_USERNAME and VPN_PASSWORD to login.,
_Starting windscribe ... OK,
Settings location to best,
Traceback (most recent call last):,
  File "/usr/bin/init.py", line 52, in <module>,
    cond = child.expect(['Please login to use Windscribe', 'Service communication error', pexpect.EOF], timeout=50),
  File "/usr/local/lib/python3.9/dist-packages/pexpect/spawnbase.py", line 343, in expect,
    return self.expect_list(compiled_pattern_list,,
  File "/usr/local/lib/python3.9/dist-packages/pexpect/spawnbase.py", line 372, in expect_list,
    return exp.expect_loop(timeout),
  File "/usr/local/lib/python3.9/dist-packages/pexpect/expect.py", line 181, in expect_loop,
    return self.timeout(e),
  File "/usr/local/lib/python3.9/dist-packages/pexpect/expect.py", line 144, in timeout,
    raise exc,
pexpect.exceptions.TIMEOUT: Timeout exceeded.,
<pexpect.pty_spawn.spawn object at 0x7f975e1a1220>,
command: /usr/bin/windscribe,
args: ['/usr/bin/windscribe', 'connect', 'best'],
buffer (last 100 chars): b'\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\',
before (last 100 chars): b'\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\\x08-\x08/\x08|\x08\\',
after: <class 'pexpect.exceptions.TIMEOUT'>,
match: None,
match_index: None,
exitstatus: None,
flag_eof: False,
pid: 143,
child_fd: 6,
closed: False,
timeout: 30,
delimiter: <class 'pexpect.exceptions.EOF'>,
logfile: None,
logfile_read: None,
logfile_send: None,
maxread: 2000,
ignorecase: False,
searchwindowsize: None,
delaybeforesend: 0.05,
delayafterclose: 0.1,
delayafterterminate: 0.1,
searcher: searcher_re:,
    0: re.compile(b'Please login to use Windscribe'),
    1: re.compile(b'Service communication error'),
    2: EOF,_

**Comment by Kabe0** [comment]
Hmm, I have not tried out WSL 2 yet, so it's possible it's something to do with Iptables etc being different

you could try added --privileged or enabling LEGACY_IPTABLES... Do you have special characters in your password that might cause issues?
 
Try logging into the container with -it /bin/bash then you can run windscribe login in the CLI directly and see if that works. Make sure it's your username pass for your account, not their openvpn details.

**Comment by L44RS** [comment]
Awesome, just enabling the privileged flag did not change anything, but enabling LEGACY_IPTABLES did! I am running ubuntu 20.04 however so I didn't think it was necessary, but apparently it was. Thanks a lot!

**Comment by Kabe0** [comment]
No problem. I am in progress with updating the container for a newer version of libtorrent. Though it might be the end of the week before I get it live due to some package issues.
