### ISSUE TITLE
Unable to access Deluge from outside

### ISSUE THREAD

**Issue by yoanndelattre** [Kabe0/deluge-windscribe#26]
I am running the container on a hosted server with the vpn enabled. 
I can access Deluge from localhost but not from its external ip.
I have already tried to enable or not the windscribe firewall but the problem persists.

**Comment by Kabe0** [comment]
What distro? Is this ARM or x86?

**Comment by yoanndelattre** [comment]
Both

**Comment by yoanndelattre** [comment]
And my distro is Ubuntu

**Comment by Kabe0** [comment]
Ah ARM is a bit finicky. What does your yml file config look like?
Also try LEGACY_IPTABLES if you have not already.

**Comment by yoanndelattre** [comment]
I have already tried activating LEGACY_IPTABLES but it didn't work. I can no longer even transfer port 8112 by ssh to connect to deluge. I think I'll use the official deluge image because I'm on a hosted server.

**Comment by Kabe0** [comment]
K, it might be the hosted server that is overriding the iptable rules causing your problems. iptables are what are used to route packets.

**Comment by yoanndelattre** [comment]
I don't think that's it. The problem is present on the hosted server and on the raspberrypi which is at my home. But the problem does not happen when the VPN is disabled.

**Comment by san-kumar** [comment]
Having the same issue. Works great if I connect via localhost but can't connect from outside. Even with LEGACY_IPTABLES options. 

Some ideas:
- Add a local proxy on the host machine to relay traffic from localhost to outside
-  There is an `extra_hosts` option in docker-compose but I'm too new to understand that option. Found it after googling.

Any suggestions would be appreciated.

**Comment by yoanndelattre** [comment]
Thanks for the idea.
But I no longer use Deluge as a download client.
So I will close this issue.

**Comment by san-kumar** [comment]
Gotcha. This is a very useful project still. Thanks for all your work.
