### ISSUE TITLE
Reuse you image

### ISSUE THREAD

**Issue by Maxl94** [Kabe0/deluge-windscribe#7]
Hi,

first of all thanks for your great windscribe docker image. I currently use parts of your repo ( for a personal image to run applications inside the container. I currently adapted the `Dockerfile` and the `init.py`.

 Would you mind if publish this image? I didn't found any license files.  Of course I would mention you.

Thanks

**Comment by Kabe0** [comment]
Sure, it's all open source.

**Comment by Maxl94** [comment]
Okay - cool. I am currently fighting windscribe... Login works perfektly on local machine but not from inside docker container..

**Comment by Kabe0** [comment]
typically that happens when the username and password are not configured correctly for the container to retrieve it. It should throw an error if it finds that windscribe-cli is unable to connect properly.

**Comment by Maxl94** [comment]
No thats not the case, I directly conntected to the container.  with bash and tried to login -> `Error running "login"`

Windscribe logs showing: 
```
2020-11-12 19:33:17,798 [INFO] Daemon: Error running "login", error: <class 'subprocess.CalledProcessError'> Command '['iptables -nL OUTPUT']' returned non-zero exit status 3
```

**Comment by Maxl94** [comment]
Fixed it: Forget `cap_add: - NET_ADMIN` to add to my compose file...
