### ISSUE TITLE
VPN_ENABLE Environment variable does not work

### ISSUE THREAD

**Issue by GeorgeArgyrakis** [Kabe0/deluge-windscribe#9]
In init.py this
` if os.getenv('VPN_ENABLE', True):` always returns true
the correct syntax must be something like that
`if os.getenv('VPN_ENABLE', True).lower() in ['true', '1']:`

**Comment by Kabe0** [comment]
Good catch! I'll patch it tonight.

**Comment by Kabe0** [comment]
1.8.8 resolves this issue
